### ISSUE TITLE
How to create ocr post correction from beginning?

### ISSUE THREAD

**Issue by arater** [nlppln/nlppln#29]
I am an intern in one company and they gave me this ocr post correction project but i am new about machine learning and python. Your project exactly does what i want but i am getting lost while analyzing where to start and which steps should i follow. I know this takes your time but it is very important for me to understand and implement this project. I hope you will help. Thanks.

**Comment by jvdzwaan** [comment]
There is documentation on how to get started with nlppln: http://nlppln.readthedocs.io/en/latest/
But I think your question refers to ochre: https://github.com/KBNLresearch/ochre, so I'll close this issue.
