### ISSUE TITLE
Make CWL types constants for tab-completion

### ISSUE THREAD

**Issue by egpbos** [nlppln/nlppln#31]
When adding inputs, it would be nice if there was a list of CWL types available in nlppln, so that I could use tab-completion when entering them, e.g.

```python
with nlppln.WorkflowGenerator() as wf:
  something = wf.add_input(something=nlppln.cwl_type. [TAB TAB TAB]
```

This way, I don't have to know all the CWL types by heart.

**Comment by jvdzwaan** [comment]
Copied issue to scriptcwl, this should be implemented there.
